name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-format-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r airflow/requirements.txt
          pip install black flake8 mypy pytest detect-secrets

      - name: Lint with flake8
        run: flake8 .

      - name: Check formatting with black
        run: black --check .

      - name: Type check with mypy
        run: mypy airflow/dags

      - name: Run tests
        run: pytest

      - name: Detect secrets
        run: detect-secrets scan --all-files > secrets_report.json && (! grep -q '"has_secrets": true' secrets_report.json)

  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfiles with hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: airflow/Dockerfile

  yaml-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check YAML files
        run: |
          pip install yamllint
          yamllint .

  doc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for README.md
        run: test -f README.md 